apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netflix-api-secret
  namespace: netflix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: netflix-api-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: my-db-secret-credentials
